@echo off

@REM echo Activating virtual environment for the first Python script...
@REM call "E:\Frank_Projects\human-factor-equipment\EEG\tmsi-python-interface-V5.1.0.0\.venv_310\Scripts\activate.bat"
@REM echo Running first Python script...
@REM "E:\Frank_Projects\human-factor-equipment\EEG\tmsi-python-interface-V5.1.0.0\.venv_310\Scripts\python.exe" "E:\Frank_Projects\human-factor-equipment\EEG\tmsi-python-interface-V5.1.0.0\examples_SAGA\example_stream_lsl.py"
@REM echo First script finished. Pausing for 30 seconds...
@REM ping 127.0.0.1 -n 31 > nul

@REM echo Running second Python script...
@REM start "Script 0" cmd /c python "E:\Frank_Projects\EEG_Neurofeedback_Frank\BCI\PSD\mock_lsl.py"
@REM echo Second script finished. Pausing for 5 seconds...
@REM ping 127.0.0.1 -n 6 > nul

echo Running second Python script...
start "Script 1" cmd /c python "E:\Frank_Projects\EEG_Neurofeedback_Frank\BCI\PSD\raw_data.py"
echo Second script finished. Pausing for 5 seconds...
ping 127.0.0.1 -n 6 > nul

echo Running second Python script...
start "Script 2" cmd /c python "E:\Frank_Projects\EEG_Neurofeedback_Frank\BCI\PSD\eeg_client_v2.py"
echo Second script finished. Pausing for 5 seconds...
ping 127.0.0.1 -n 6 > nul

echo Running third Python script...
start "Script 3" cmd /c python "E:\Frank_Projects\EEG_Neurofeedback_Frank\beeping\server_loudness_v2.py"
ping 127.0.0.1 -n 6 > nul

echo Changing directory to E:\Carla_Neurofeedback
cd /d E:\Carla_Neurofeedback
echo Running control.py script in 'carla' environment...
start "Carla Control" python control.py

echo All scripts have been executed concurrently.
